### PR TITLE
IObservableList items as IReadOnlyList

### PR DESCRIPTION
**Pull request by kronic**
Changes the `Items` property in `IObservableList<T>` from `IEnumerable<T>` to `IReadOnlyList<T>`.

### CODE REVIEW

**Review by dwcullop — APPROVED** [review]
I think this is an okay breaking change.

**Comment by RolandPheasant** [comment]
Looks fine to me

**Comment by RolandPheasant** [comment]
Dare I say, that we should probably to the same for cache.

**Comment by kronic** [comment]
@RolandPheasant ok

**Comment by JakenVeina** [comment]
@kronic Need conflicts resolved, if you're still interested in getting this merged.

**Pull request merged**
